### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by timedoutuk** [Tyman-productions/Utilibot#8]
I was reading through c4ddfbe, and saw you were doing raw queries.

Are you still using JSON?
if not, have you considered using an ORM, like gino? atm it only supports postgres, but iirc `sqlalchemy` supports sqlite and allows for a better oop experience along with more org.

If you need any help let me know, I can open a PR with it all modled for you if you wanted.

**Comment by TymanWasTaken** [comment]
Right now it does use raw sql queries, and json in an sql table for logging data for guilds. If you want to help with an ORM go ahead, I can look into that

**Comment by timedoutuk** [comment]
Sounds good

**Comment by TymanWasTaken** [comment]
when v2 is the main bot this won't matter because I am using an orm in it
